[package]
name = "finalizable"
version = "0.1.1"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "A type for finalizable values"
repository = "https://github.com/schuelermine/finalizable"
keywords = ["no-std"]
categories = ["no-std", "no-std::no-alloc"]
